# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:


- job: appbuild
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: 
      sudo apt install curl zip unzip tar bzip2 -y; 
      wget -O buildpack.zip $(DOCKER_BUILDPACK_URL);
      unzip buildpack.zip;
      sudo mv docker-mendix-buildpack*/* .;
      echo "THESE ARE ALL THE FILES and DIRECTORIES";
      find . -maxdepth 3;
      echo "BUILDING WITH BUILD.PY";
      mkdir buildoutput;
      echo "IS THERE A PY AND MDA DIR?";
      ls;
      sudo ./build.py --source ./ --destination ./buildoutput/ build-mda-dir;
      echo "ALL FILES HERE??";  
      find ./buildoutput/ -maxdepth 2;
      echo "BUILDING WITH DOCKERBUILD";
      sudo docker build --build-arg ROOTFS_IMAGE=lombardog/mendix-rootfs1:app --build-arg BUILDER_ROOTFS_IMAGE=lombardog/mendix-rootfs1:builder --tag lombardog/$(MENDIXAPPNAME):0.0.1 buildoutput/;
      echo "LOGIN TO DOCKER";
      sudo docker login -u $(DOCKER_LOGIN) -p $(DOCKER_PASSWORD);
      echo "PUSHING TO DOCKER";
      sudo docker push lombardog/$(MENDIXAPPNAME):1.0.0;