# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

jobs:

#- job: rootfs
#  pool:
#    vmImage: 'ubuntu-latest'
#  steps:
#  - script: 
#      sudo apt install curl zip unzip tar bzip2 -y;
#      wget -O buildpack.zip $(DOCKER_BUILDPACK_URL);
#      unzip buildpack.zip;
#      sudo mv docker-mendix-buildpack*/* . ;
#      docker build -t lombardog/mendix-rootfs1:app -f rootfs-builder.dockerfile .;
#      docker build -t lombardog/mendix-rootfs1:builder -f rootfs-app.dockerfile .;
#      sudo docker login -u $(DOCKER_LOGIN) -p $(DOCKER_PASSWORD);
#      sudo docker push lombardog/mendix-rootfs1:app;
#      sudo docker push lombardog/mendix-rootfs1:builder;


- job: appbuild
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: 
      sudo apt install curl zip unzip tar bzip2 -y; 
      wget -O buildpack.zip $(DOCKER_BUILDPACK_URL);
      unzip buildpack.zip;
      echo "MOVINGDOCKER"
      sudo mv docker-mendix-buildpack*/* .;
      pwd;
      echo "THESE ARE ALL THE FILES and DIRECTORIES";
      find . -maxdepth 3;
      echo "BUILDING WITH BUILD.PY";
      cd docker-mendix-buildpack-6.0.1;
      echo "IS THERE A PY AND MDA DIR?";
      mkdir mda;
      ls;
      sudo ./build.py --source ../ --destination ./mda/ build-mda-dir;
      echo "IS THERE MDA??";  
      ls ./mda/;
      echo "IS THERE dockerfile??";
      ls;
      echo "BUILDING WITH DOCKERBUILD";
      docker build --build-arg ROOTFS_IMAGE=lombardog/mendix-rootfs1:app --build-arg BUILDER_ROOTFS_IMAGE=lombardog/mendix-rootfs1:builder --tag lombardog/$(MENDIXAPPNAME):1.0.0 ./mda/;
      echo "LOGIN TO DOCKER";
      docker login -u $(DOCKER_LOGIN) -p $(DOCKER_PASSWORD);
      echo "PUSHING TO DOCKER";
      docker push lombardog/$(MENDIXAPPNAME):1.0.0;